### ISSUE TITLE
Unable to use 3.0.0 or 4.0.0 using Docker and Ruby 2.5-alpine

### ISSUE THREAD

**Issue by Eric-Fontana-Bose** [abonas/kubeclient#354]
I tried both version 3.0.0 and 4.0.0 and using the Docker image ruby-2.5-alpine

/lib/kubeclient/common.rb:221:in `rest_client': undefined method `path' for nil:NilClass (NoMethodError)

My Gemfile has:
```ruby
source 'https://rubygems.org'
gem 'kubeclient'
gem 'json-schema'
gem 'filewatcher'
gem 'rest-client'
```
Any ideas? Works fine with the ruby-2.5 image, but it's huge.

**Comment by cben** [comment]
Sorry for silence, haven't had time to reproduce.  Does this reoccur?
Can you show how exactly you're constructing Kubeclient::Client? 

The error message points at this line:
```
      create_rest_client("#{@api_endpoint.path}/#{@api_version}")
```
so `@api_endpoint` is nil.  It's set in `handle_uri` called from constructor:
```
    @api_endpoint = (uri.is_a?(URI) ? uri : URI.parse(uri))
```
So looks like you're calling `Client.new()` with first arg on which `URI.parse('...')` returns nil?
But according to docs, that's not really supposed to happen (should raise exception if invalid) :confused: 

--- 
I tried a couple calls in bare ruby in a `ruby:2.5-alpine` container and I can't seem to get nil:
```
irb(main):005:0> URI.parse('https://localhost/api:8001')
=> #<URI::HTTPS https://localhost/api:8001>
irb(main):006:0> URI.parse('example.com')
=> #<URI::Generic example.com>
irb(main):003:0> URI.parse('')
=> #<URI::Generic >
irb(main):004:0> URI.parse(nil)
Traceback ...
URI::InvalidURIError (bad URI(is not URI?): )
```
I tried bundler with Gemfile you gave inside this container, but got error:
```
An error occurred while installing unf_ext (0.0.7.5), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.5' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  kubeclient was resolved to 4.2.1, which depends on
    http was resolved to 3.3.0, which depends on
      http-cookie was resolved to 1.0.3, which depends on
        domain_name was resolved to 0.5.20180417, which depends on
          unf was resolved to 0.1.4, which depends on
            unf_ext
```

Can you provide your exact Dockerfile & Gemfile.lock?

**Comment by cben** [comment]
@Eric-Fontana-Bose friendly ping — is this still a problem for you?
Can you provide more detail?
Without more detail, I'm gonna close as "can't reproduce".  My current best guess is wrong params constructing Kubeclient::Client, though I don't quite see how it got that error.

**Comment by mnohai-mdsol** [comment]
I too am receiving this issue when its running ```bundle install``` inside the ```ruby:2.5.3-alpine3.8``` image. I tried forcing bundler to use the latest version, the outcome is the same.

**Comment by tornglintaffychen** [comment]
Yup, ended up adding `RUN apk add --upgrade build-base ruby-dev --no-cache` to our Dockerfile.
(using `ruby:2.5.5-alpine3.8`)

**Comment by cben** [comment]
Nice.  I'm closing as this sounds like simply matter of using ruby alpine image correctly.
Please reopen if you think kubeclient can do something to improve this.
